development:
  adapter: redis
  url: redis://127.0.0.1:6379/0

test:
  adapter: redis
  url: redis://127.0.0.1:6379/0

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: CableChat_production
